version: '3.8'

services:
  db:
    build:
      dockerfile: 'Dockerfile'
      context: 'migration'
      args:
        - DB_USER=$DB_USER
        - DB_PASSWORD=$DB_PASSWORD
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}