version: '3.8'

services:
  db:
    restart: always
    container_name: database
    build:
      dockerfile: 'Dockerfile'
      context: './migration'
      args:
        - DB_USER=$DB_USER
        - DB_PASSWORD=$DB_PASSWORD
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    restart: always
    container_name: backend
    build:
      dockerfile: 'Dockerfile'
      context: './backend'
    ports:
      - '8080:8080'
    environment:
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_PORT=$DB_PORT
      - BACKEND_PORT=$BACKEND_PORT
      - DB_DATABASE_NAME=$DB_DATABASE_NAME
      - DB_HOST=$DB_HOST
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    links:
      - db

  frontend:
    restart: always
    container_name: frontend
    build:
      dockerfile: 'Dockerfile'
      context: './frontend'
    ports:
      - '3000:80'

volumes:
  pgdata: { }