version: '3.8'

services:
  db:
    restart: always
    container_name: database
    build:
      dockerfile: 'Dockerfile'
      context: './migration'
      args:
        - DB_USER=$DB_USER
        - DB_PASSWORD=$DB_PASSWORD
    ports:
      - '5432:5432'

  backend:
    restart: always
    container_name: backend
    build:
      dockerfile: 'Dockerfile'
      context: './backend'
    ports:
      - '8080:8080'
    environment:
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_PORT=5432
      - BACKEND_PORT=8080
      - DB_DATABASE_NAME=postgres
      - DB_HOST=db
    links:
      - db

  frontend:
      restart: always
      container_name: frontend
      build:
        dockerfile: 'Dockerfile'
        context: './frontend'
      ports:
        - '3000:80'