swagger: "2.0"
info:
  description: "This is the API specification of the Helsinki bike trips application, part of the Solita pre-assignment for Fall 2022"
  version: "1.0.0"
  title: "Helsinki bike trips"
  contact:
    email: "cristiannicolae.lupascu@efu.turkuamk.fi"
basePath: "/"
tags:
- name: "Station"
  description: "Access to station data"
- name: "Trip"
  description: "Access to trip data"
schemes:
- "http"
paths:
  /stations:
    get:
      tags:
      - "Station"
      summary: "Finds all stations"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Station"
  /stations/{stationId}:
    get:
      tags:
      - "Station"
      summary: "Fetch station details based on given station ID"
      description: "Returns a single station"
      produces:
      - "application/json"
      parameters:
      - name: "stationId"
        in: "path"
        description: "Unique ID of the station to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Station"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Station not found"
  /stations/{stationId}/stats:
    get:
      tags:
      - "Station"
      summary: "Fetch station statistics based on given station ID"
      description: "Returns a single statistic"
      produces:
      - "application/json"
      parameters:
      - name: "stationId"
        in: "path"
        description: "Unique ID of the station"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: '#/definitions/StationStatistics'
        "400":
          description: "Invalid IDsupplied"
        "404":
          description: "Station not found"




definitions:
  Trip:
    type: "object"
    properties:
      departure_time:
        type: "string"
        format: "date-time"
        description: "The date and time at which the trip started"
      return_time:
        type: "string"
        format: "date-time"
        description: "The date and time at which the trip ended"
      departure_station:
        type: "integer"
        format: "int64"
        description: "The ID of the starting station"
      return_station:
        type: "integer"
        format: "int64"
        description: "The ID of the ending station"
      distance:
        type: "number"
        format: "float32"
        description: "The total distance done during the trip"
      duration:
        type: "integer"
        format: "int64"
        description: "The total amount of seconds done during the trip"
  Station:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "The unique id of the station"
      name_fi:
        type: "string"
        description: "The name of the station in Finnish"
      name_se:
        type: "string"
        description: "The name of the station in Swedish"
      name_en:
        type: "string"
        description: "The name of the station in English"
      address_fi:
        type: "string"
        description: "The address of the station in Finnish"
      address_se:
        type: "string"
        description: "The address of the station in Swedish"
      city_fi:
        type: "string"
        description: "The city in which the station is located in Finnish"
      city_se:
        type: "string"
        description: "The city in which the station is located in Swedish"
      operator:
        type: "string"
        description: "The name of the operator that owns and mantains the station"
      capacity:
        type: "integer"
        format: "int64"
        description: "The total bike capacity of the station"
      coordinates:
        type: "object"
        description: "The geographical coordinates of the station"
        properties:
          x:
            type: "number"
            format: "float32"
            description: "The latitudinal coordinate"
          y:
            type: "number"
            format: "float32"
            description: "The longitudinal coordinate"
  StationStatistics:
    type: "object"
    description: "A series of statistics regarding a single station"
    properties:
      total_inbound:
        type: "integer"
        format: "int64"
        description: "The total amount of trips which end in this station"
      total_outbound:
        type: "integer"
        format: "int64"
        description: "The total amount of trips which start in this station"
      average_distance_inbound:
        type: "integer"
        format: "int64"
        description: "The average distance of the trips which end in this station"
      average_distance_outbound:
        type: "integer"
        format: "int64"
        description: "The average distance of the trips which start in this station"
      top_inbound:
        type: "array"
        maxItems: 5
        items:
          $ref: "#/definitions/Trip"
        description: "The top 5 stations which have trips ending in this station"
      top_outbound:
        type: "array"
        maxItems: 5
        items:
          $ref: "#/definitions/Trip"
        description: "The top 5 stations which have trips starting in this station"