swagger: "2.0"
info:
  description: "This is the API specification of the Helsinki bike trips application, part of the Solita pre-assignment for Fall 2022"
  version: "1.0.0"
  title: "Helsinki bike trips"
  contact:
    email: "cristiannicolae.lupascu@efu.turkuamk.fi"
schemes:
- "http"
paths:
  /stations:
    $ref: './paths/stations.yaml'
  /stations/{stationId}:
    $ref: './paths/station/station.yaml'
  /stations/{stationId}/stats:
    $ref: './paths/station/statistics.yaml'
  /trips:
    $ref: './paths/trips.yaml'

definitions:
  station:
    $ref: './schemas/station.yaml'
  trip:
    $ref: './schemas/trip.yaml'
  stats:
    $ref: './schemas/statistics.yaml'
  error:
    $ref: './schemas/error.yaml'
  station page:
    $ref: './schemas/station_page.yaml'
  trips page:
    $ref: './schemas/trips_page.yaml'